# Mozilla Guideline v5.7, nginx 1.28.3, OpenSSL 3.6.1, intermediate configuration
#
# @see https://ssl-config.mozilla.org/#server=nginx&version=1.28.3&config=intermediate&openssl=3.6.1&ocsp=false&guideline=5.7

# Adds HSTS (HTTP Strict Transport Security) to avoid SSL stripping.
add_header Strict-Transport-Security 'max-age=63072000' always;
