# Mozilla Guideline v5.7, nginx 1.30.1, OpenSSL 3.5.5, intermediate configuration
#
# @see https://ssl-config.mozilla.org/#server=nginx&version=1.30.1&config=intermediate&openssl=3.5.5&hsts&guideline=5.7

# Adds HSTS (HTTP Strict Transport Security) to avoid SSL stripping.
add_header Strict-Transport-Security 'max-age=63072000' always;
