# TLSRef Guideline v6.0, nginx 1.30.2, OpenSSL 3.5.5, intermediate configuration, HSTS
#
# @see https://configurator.tlsref.org/#server=nginx&version=1.30.2&config=intermediate&openssl=3.5.5&hsts&guideline=6.0

# Adds HSTS (HTTP Strict Transport Security) to avoid SSL stripping.
add_header Strict-Transport-Security 'max-age=63072000' always;
