name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '1.26/**'
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-24.04]

    strategy:
      fail-fast: false
      matrix:
        version: [1.26-bookworm]
        include:
          - version: 1.26-bookworm
            docker-context: 1.26/debian/default
            docker-tags: |
              nicoherbigde/nginx-proxy:1.26
              nicoherbigde/nginx-proxy:1.26-bookworm
              nicoherbigde/nginx-proxy:1.26.2
              nicoherbigde/nginx-proxy:1.26.2-bookworm

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
