name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '1.20/**'
      - '1.22/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [1.20, 1.22]
        include:
          - version: 1.20
            docker-context: 1.20/debian/default
            docker-tags: |
              nicoherbigde/nginx-proxy:1.20
              nicoherbigio/nginx-proxy:1.20
              nicoherbigde/nginx-proxy:1.20.2
              nicoherbigio/nginx-proxy:1.20.2
          - version: 1.22
            docker-context: 1.22/debian/default
            docker-tags: |
              nicoherbigde/nginx-proxy:1.22
              nicoherbigio/nginx-proxy:1.22
              nicoherbigde/nginx-proxy:1.22.0
              nicoherbigio/nginx-proxy:1.22.0

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          push: true
          tags: ${{ matrix.docker-tags }}
